#!/usr/bin/python3
"""Summarize README.md files in subdirectories using a local LLM.

The output file is a self-contained Python script: a small viewer at the top,
the summaries embedded below it as JSON. Run the output file to browse them.
"""

import argparse
import json
import os
import re
import stat
from datetime import datetime, timezone
from sys import stderr
from typing import Any

import requests

# LM Studio endpoint - adjust if your server runs elsewhere
LLM_URL: str = "http://127.0.0.1:1234/v1/chat/completions"
LLM_MODEL: str = "qwen/qwen3.6-35b-a3b"

# Max characters of README content to send to the LLM
README_LIMIT: int = 65536

# Seconds to wait for the LLM before giving up. Longer summaries take longer,
# so this is well above the old 60s.
LLM_TIMEOUT: int = 300

SYSTEM_PROMPT: str = (
    "You are a technical writer summarizing software project documentation. "
    "You are accurate and never invent details that are not in the source."
)

USER_PROMPT: str = (
    "Write a detailed summary of the following project README.\n"
    "Cover these points, in this order, as flowing prose:\n"
    "1. What the project is and what problem it solves.\n"
    "2. Its main features and capabilities.\n"
    "3. The languages, frameworks, and notable dependencies it uses.\n"
    "4. How it is built, installed, configured, and run.\n"
    "5. Anything notable about its status, license, platform support, or "
    "known limitations.\n\n"
    "Aim for four to six paragraphs. If the README does not cover one of the "
    "points above, skip that point rather than guessing. Use plain text only: "
    "no markdown, no headings, no bullet lists, no code fences.\n\n"
    "README follows:\n\n"
)

# Some reasoning models emit a visible thinking block. Strip it if present.
THINK_RE = re.compile(r"<think>.*?</think>\s*", re.DOTALL | re.IGNORECASE)

VIEWER_PREFIX: str = '''#!/usr/bin/env python3
"""Repo summary browser.

Generated by summarize_repos.py - regenerate rather than editing by hand.

Usage:
    ./summaries.py            interactive menu
    ./summaries.py NAME       print one summary and exit
    ./summaries.py --list     print the repo names and exit
    ./summaries.py --json     dump the raw JSON and exit
"""

import json
import shutil
import sys
import textwrap

_DATA = r"""
'''

VIEWER_SUFFIX: str = '''"""


def load_data():
    try:
        return json.loads(_DATA)
    except ValueError as ex:
        sys.stderr.write("Embedded summary data is corrupt: %s\\n" % ex)
        raise SystemExit(1)


def term_width():
    width = shutil.get_terminal_size((80, 24)).columns - 2
    return max(40, min(width, 100))


def wrap(text):
    width = term_width()
    out = []
    for para in text.split("\\n"):
        para = para.strip()
        out.append(textwrap.fill(para, width=width) if para else "")
    return "\\n".join(out)


def show(name, entry):
    width = term_width()
    print()
    print("=" * width)
    print(name)
    print("=" * width)
    print()
    print(wrap(entry.get("summary", "(no summary)")))
    print()


def print_menu(names, meta):
    width = term_width()
    print()
    print("=" * width)
    print("Repo summaries (%d) - generated %s by %s"
          % (len(names), meta.get("generated", "?"), meta.get("model", "?")))
    print("=" * width)
    pad = len(str(len(names)))
    for index, name in enumerate(names, start=1):
        print("%*d. %s" % (pad, index, name))
    print()


def menu(names, repos, meta):
    while True:
        print_menu(names, meta)
        try:
            choice = input("Choose a repo by number or name (q to quit): ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return

        if choice.lower() in ("q", "quit", "exit"):
            return
        if not choice:
            continue

        name = resolve(choice, names)
        if name is None:
            print("\\nNo such repo: %s" % choice)
            continue

        show(name, repos[name])
        try:
            input("Press Enter to return to the menu... ")
        except (EOFError, KeyboardInterrupt):
            print()
            return


def resolve(choice, names):
    if choice.isdigit():
        index = int(choice)
        if 1 <= index <= len(names):
            return names[index - 1]
        return None
    lowered = choice.lower()
    for name in names:
        if name.lower() == lowered:
            return name
    matches = [name for name in names if name.lower().startswith(lowered)]
    if len(matches) == 1:
        return matches[0]
    return None


def main(argv):
    data = load_data()
    repos = data.get("repos", {})
    names = sorted(repos)
    meta = {"generated": data.get("generated", "?"), "model": data.get("model", "?")}

    if not names:
        print("No summaries in this file.")
        return 0

    if argv:
        arg = argv[0]
        if arg in ("-h", "--help"):
            print(__doc__.strip())
            return 0
        if arg in ("-j", "--json"):
            print(json.dumps(data, indent=2))
            return 0
        if arg in ("-l", "--list"):
            for name in names:
                print(name)
            return 0
        name = resolve(arg, names)
        if name is None:
            sys.stderr.write("No such repo: %s\\n" % arg)
            return 1
        show(name, repos[name])
        return 0

    menu(names, repos, meta)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''


def get_dirs(base_dir: str = ".") -> list[str]:
    """Return a sorted list of non-hidden subdirectory names in base_dir."""
    dirs: list[str] = []
    with os.scandir(base_dir) as it:
        for entry in it:
            if not entry.name.startswith(".") and entry.is_dir():
                dirs.append(entry.name)
    return sorted(dirs)


def pull_readme(base_dir: str, dir_name: str) -> tuple[str, bool]:
    """Return (contents, truncated) for README.md in base_dir/dir_name, or ('', False)."""
    full_dir: str = os.path.join(base_dir, dir_name)
    try:
        entries: list[str] = os.listdir(full_dir)
    except OSError:
        return "", False

    for entry in entries:
        if entry.lower() == "readme.md":
            readme_path: str = os.path.join(full_dir, entry)
            try:
                with open(
                    readme_path, "r", encoding="utf-8", errors="replace"
                ) as f:
                    content: str = f.read()
                if len(content) > README_LIMIT:
                    stderr.write(
                        f"[warning] {dir_name}/README.md truncated to {README_LIMIT} chars\n"
                    )
                    return content[:README_LIMIT], True
                return content, False
            except OSError:
                return "", False
    return "", False


def pull_ai(
    text: str, session: requests.Session, url: str, model: str, timeout: int
) -> str:
    """Send text to the local LLM and return a detailed summary, or '' on failure."""
    payload: dict[str, Any] = {
        "model": model,
        "temperature": 0.4,
        "max_tokens": -1,
        "stream": False,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": USER_PROMPT + text},
        ],
    }
    try:
        response: requests.Response = session.post(
            url, json=payload, timeout=timeout
        )
        response.raise_for_status()
        resp_json: dict[str, Any] = response.json()
        summary: str = str(resp_json["choices"][0]["message"]["content"])
        return THINK_RE.sub("", summary).strip()
    except requests.exceptions.Timeout:
        stderr.write(f"\n[error] LLM request timed out after {timeout}s\n")
        return ""
    except requests.exceptions.RequestException as ex:
        stderr.write(f"\n[error] LLM network/HTTP error: {ex}\n")
        return ""
    except (KeyError, IndexError, ValueError) as ex:
        stderr.write(f"\n[error] Unexpected LLM response format: {ex}\n")
        return ""


def render_output(data: dict[str, Any]) -> str:
    """Return the full text of the self-contained viewer script."""
    # ensure_ascii keeps the blob pure ASCII, and JSON escaping guarantees it
    # can never contain a triple quote, so the raw string below is always safe.
    blob: str = json.dumps(data, indent=2, sort_keys=True, ensure_ascii=True)
    if '"""' in blob:
        raise ValueError("summary data contains a triple quote, cannot embed")
    return VIEWER_PREFIX + blob + "\n" + VIEWER_SUFFIX


def make_executable(path: str) -> None:
    try:
        mode = os.stat(path).st_mode
        os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError as ex:
        stderr.write(f"[warning] could not mark {path} executable: {ex}\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Summarize README.md files in subdirectories using a local LLM."
    )
    parser.add_argument(
        "-d", "--directory", help="The base directory to scan", required=True
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output script (default: summaries.py in the scanned directory)",
        default=None,
    )
    parser.add_argument(
        "-u", "--url", help="LLM endpoint URL", default=LLM_URL
    )
    parser.add_argument(
        "-m", "--model", help="LLM model name", default=LLM_MODEL
    )
    parser.add_argument(
        "-t",
        "--timeout",
        type=int,
        help=f"Seconds to wait per request (default: {LLM_TIMEOUT})",
        default=LLM_TIMEOUT,
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Do not echo each summary while working",
    )
    args = parser.parse_args()

    basedir: str = args.directory
    output_path: str = args.output or os.path.join(basedir, "summaries.py")

    repos: dict[str, dict[str, Any]] = {}
    failed: list[str] = []

    with requests.Session() as session:
        for subdir in get_dirs(basedir):
            text, truncated = pull_readme(basedir, subdir)
            if not text:
                continue
            print(f"[{subdir}] summarizing {len(text)} chars...", flush=True)
            summary: str = pull_ai(
                text, session, args.url, args.model, args.timeout
            )
            if summary:
                repos[subdir] = {
                    "summary": summary,
                    "readme_chars": len(text),
                    "readme_truncated": truncated,
                }
                if not args.quiet:
                    print(f"{subdir}: {summary}\n")
            else:
                failed.append(subdir)

    if repos:
        data: dict[str, Any] = {
            "generated": datetime.now(timezone.utc).strftime(
                "%Y-%m-%d %H:%M:%SZ"
            ),
            "model": args.model,
            "source_directory": os.path.abspath(basedir),
            "repos": repos,
        }
        with open(output_path, "w", encoding="utf-8") as out:
            out.write(render_output(data))
        make_executable(output_path)
        print(f"Wrote {len(repos)} summaries to: {output_path}")
        print(
            f"Run it with: {output_path if os.path.isabs(output_path) else './' + output_path}"
        )
    else:
        print("No summaries to write.")

    if failed:
        print(f"Failed: {sorted(failed)}")

    return 1 if failed and not repos else 0


if __name__ == "__main__":
    raise SystemExit(main())
